-- AlterTable
ALTER TABLE `user` ALTER COLUMN `phoneNumber` DROP DEFAULT,
    MODIFY `postalCode` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `address` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `firstName` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `lastName` VARCHAR(191) NOT NULL DEFAULT '';
